env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - airbnb-typescript
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - import
settings:
  react:
    version: detect
rules:
  typescript-eslint/no-use-before-define: off
  react/jsx-filename-extension:
    [1, { 'extensions': ['.tsx', '.ts', '.json', 'yml'] }]
